"""empty message

Revision ID: 2a247c57fa17
Revises: 
Create Date: 2020-02-24 11:23:36.801621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a247c57fa17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analisis_unitario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=False),
    sa.Column('unidad', sa.String(length=5), nullable=False),
    sa.Column('grupo', sa.String(length=10), nullable=True),
    sa.Column('clasificacion', sa.String(length=20), nullable=True),
    sa.Column('valorUnitario', sa.Float(), nullable=False),
    sa.Column('costoMateriales', sa.Float(), nullable=False),
    sa.Column('costoEquipo', sa.Float(), nullable=False),
    sa.Column('costoManoObra', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('proyecto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_Obra', sa.String(length=100), nullable=False),
    sa.Column('contratante', sa.String(length=100), nullable=False),
    sa.Column('proponente', sa.String(length=100), nullable=False),
    sa.Column('fecha_Presentacion', sa.Date(), nullable=False),
    sa.Column('fecha_Modificacion', sa.Date(), nullable=False),
    sa.Column('comentarios', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recurso_basico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.Column('unidad', sa.String(length=5), nullable=True),
    sa.Column('grupo', sa.String(length=5), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('capitulo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyecto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('costo_indirecto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=50), nullable=False),
    sa.Column('porcentaje', sa.Float(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyecto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=50), nullable=False),
    sa.Column('unidad', sa.String(length=5), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('aporte', sa.Float(), nullable=False),
    sa.Column('valor_unitario', sa.Float(), nullable=False),
    sa.Column('numero_capitulo', sa.Integer(), nullable=True),
    sa.Column('capitulo_id', sa.Integer(), nullable=True),
    sa.Column('costoMateriales', sa.Float(), nullable=False),
    sa.Column('costoEquipo', sa.Float(), nullable=False),
    sa.Column('costoManoObra', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['capitulo_id'], ['capitulo.id'], ),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyecto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analisis_unitario_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('rendimiento', sa.Float(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=50), nullable=False),
    sa.Column('unidad', sa.String(length=5), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('grupo', sa.String(length=5), nullable=True),
    sa.Column('desperdicio', sa.Float(), nullable=False),
    sa.Column('detalleDe', sa.String(length=10), nullable=False),
    sa.Column('subTotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['analisis_unitario_id'], ['analisis_unitario.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle')
    op.drop_table('item')
    op.drop_table('costo_indirecto')
    op.drop_table('capitulo')
    op.drop_table('recurso_basico')
    op.drop_table('proyecto')
    op.drop_table('analisis_unitario')
    # ### end Alembic commands ###
